// roleSettingsConfig.js
// label/badge/identifierLabel/createdByLabel values are i18n translation keys

export const ROLE_SETTINGS = {
  citizen: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: false,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'settings.identifiers.citizenId',
      showDesignation: false,
      designationReadOnly: true,
      showCreatedBy: false,
      createdByLabel: '',
      showVerificationStatus: false,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: false,
      showSmsOtp: false,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: true,
      triggers: [
        { k: 'appointmentStatus', label: 'settings.triggers.citizenAppointmentStatus' },
        { k: 'grievanceStatus', label: 'settings.triggers.citizenGrievanceStatus' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  admin: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: true,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'settings.identifiers.username',
      showDesignation: false,
      designationReadOnly: true,
      showCreatedBy: true,
      createdByLabel: 'settings.identifiers.createdByMasterAdmin',
      showVerificationStatus: false,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: false,
      showSmsOtp: false,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: true,
      triggers: [
        { k: 'newTask', label: 'settings.triggers.adminNewTask' },
        { k: 'moved', label: 'settings.triggers.adminMoved' },
        { k: 'deadline', label: 'settings.triggers.adminDeadline', deadline: true },
        { k: 'escalation', label: 'settings.triggers.adminEscalation', badge: 'settings.triggers.badgeCritical', badgeType: 'danger' },
        { k: 'approval', label: 'settings.triggers.adminApproval', badge: 'settings.triggers.badgeActionRequired', badgeType: 'warn' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  masteradmin: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: true,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'settings.identifiers.username',
      showDesignation: true,
      designationReadOnly: true,
      showCreatedBy: false,
      createdByLabel: '',
      showVerificationStatus: false,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: true,
      showSmsOtp: true,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: false,
      triggers: [
        { k: 'adminCreated', label: 'settings.triggers.masteradminAdminCreated' },
        { k: 'deoCreated', label: 'settings.triggers.masteradminDeoCreated' },
        { k: 'accountVerified', label: 'settings.triggers.masteradminAccountVerified' },
        { k: 'escalation', label: 'settings.triggers.masteradminEscalation', badge: 'settings.triggers.badgeCritical', badgeType: 'danger' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  minister: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: false,
      phoneReadOnly: false,
      showIdentifier: false,
      identifierLabel: '',
      showDesignation: true,
      designationReadOnly: true,
      showCreatedBy: false,
      createdByLabel: '',
      showVerificationStatus: false,
      showDigitalSignature: true,
      showDelegation: true,
      show2FA: true,
      showSmsOtp: true,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: true,
      triggers: [
        { k: 'newAppointment', label: 'settings.triggers.ministerNewAppointment' },
        { k: 'appointmentChange', label: 'settings.triggers.ministerAppointmentChange' },
        { k: 'deadline', label: 'settings.triggers.ministerDeadline', deadline: true },
        { k: 'escalation', label: 'settings.triggers.ministerEscalation', badge: 'settings.triggers.badgeCritical', badgeType: 'danger' },
        { k: 'approval', label: 'settings.triggers.ministerApproval', badge: 'settings.triggers.badgeActionRequired', badgeType: 'warn' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  deo: {
    profile: {
      nameReadOnly: true,
      emailReadOnly: true,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'settings.identifiers.username',
      showDesignation: false,
      designationReadOnly: true,
      showCreatedBy: true,
      createdByLabel: 'settings.identifiers.createdBy',
      showVerificationStatus: true,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: false,
      showSmsOtp: false,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: false,
      triggers: [
        { k: 'newTask', label: 'settings.triggers.deoNewTask' },
        { k: 'deadline', label: 'settings.triggers.deoDeadline', deadline: true },
      ],
      digestOptions: ['daily', 'weekly'],
    },
  },
};

export function getRoleSettings(role) {
  return ROLE_SETTINGS[role] ?? ROLE_SETTINGS.citizen;
}
