// roleSettingsConfig.js

export const ROLE_SETTINGS = {
  citizen: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: false,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'Citizen ID',
      showDesignation: false,
      designationReadOnly: true,
      showCreatedBy: false,
      createdByLabel: '',
      showVerificationStatus: false,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: false,
      showSmsOtp: false,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: true,
      triggers: [
        { k: 'meetingStatus', label: 'Meeting status updates (accepted, scheduled, cancelled)' },
        { k: 'complaintStatus', label: 'Complaint status updates (assigned, resolved, escalated)' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  admin: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: true,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'Username',
      showDesignation: false,
      designationReadOnly: true,
      showCreatedBy: true,
      createdByLabel: 'Created By (MasterAdmin)',
      showVerificationStatus: false,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: false,
      showSmsOtp: false,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: true,
      triggers: [
        { k: 'newTask', label: 'New case assigned or received in the work queue' },
        { k: 'moved', label: 'Case progressed to next stage in the workflow' },
        { k: 'deadline', label: 'Case approaching its due date', deadline: true },
        { k: 'escalation', label: 'Automatic escalation triggered for overdue case', badge: 'Critical', badgeType: 'danger' },
        { k: 'approval', label: 'Case is awaiting your action', badge: 'Action Required', badgeType: 'warn' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  masteradmin: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: true,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'Username',
      showDesignation: true,
      designationReadOnly: true,
      showCreatedBy: false,
      createdByLabel: '',
      showVerificationStatus: false,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: true,
      showSmsOtp: true,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: false,
      triggers: [
        { k: 'adminCreated', label: 'New Admin account created under the portal' },
        { k: 'deoCreated', label: 'New DEO account created under the portal' },
        { k: 'accountVerified', label: 'Admin or DEO account verified for the first time' },
        { k: 'escalation', label: 'System-level escalation or anomaly alert', badge: 'Critical', badgeType: 'danger' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  minister: {
    profile: {
      nameReadOnly: false,
      emailReadOnly: false,
      phoneReadOnly: false,
      showIdentifier: false,
      identifierLabel: '',
      showDesignation: true,
      designationReadOnly: true,
      showCreatedBy: false,
      createdByLabel: '',
      showVerificationStatus: false,
      showDigitalSignature: true,
      showDelegation: true,
      show2FA: true,
      showSmsOtp: true,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: true,
      triggers: [
        { k: 'newMeeting', label: 'New meeting scheduled on my calendar' },
        { k: 'meetingChange', label: 'Meeting cancelled or rescheduled' },
        { k: 'deadline', label: 'Upcoming meeting reminder (N days before)', deadline: true },
        { k: 'escalation', label: 'Escalation alert triggered for a pending task', badge: 'Critical', badgeType: 'danger' },
        { k: 'approval', label: 'Task is awaiting my approval or action', badge: 'Action Required', badgeType: 'warn' },
      ],
      digestOptions: ['realtime', 'daily', 'weekly'],
    },
  },
  deo: {
    profile: {
      nameReadOnly: true,
      emailReadOnly: true,
      phoneReadOnly: false,
      showIdentifier: true,
      identifierLabel: 'Username',
      showDesignation: false,
      designationReadOnly: true,
      showCreatedBy: true,
      createdByLabel: 'Created By',
      showVerificationStatus: true,
      showDigitalSignature: false,
      showDelegation: false,
      show2FA: false,
      showSmsOtp: false,
      showChangePassword: true,
    },
    notifications: {
      showSmsChannel: false,
      triggers: [
        { k: 'newTask', label: 'New citizen verification task assigned to me' },
        { k: 'deadline', label: 'Verification task deadline approaching', deadline: true },
      ],
      digestOptions: ['daily', 'weekly'],
    },
  },
};

export function getRoleSettings(role) {
  return ROLE_SETTINGS[role] ?? ROLE_SETTINGS.citizen;
}
